// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: lpbsnlixdwjxmsxxetbr

class SupabaseConfig {
  static const String supabaseUrl = 'https://lpbsnlixdwjxmsxxetbr.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwYnNubGl4ZHdqeG1zeHhldGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjM0MTYsImV4cCI6MjA5MTAzOTQxNn0.nn76uG8Kb-LZc4vWGZSaL-QpvhyWUkB5t4uw-BP3zlM';
}
